### ISSUE TITLE
Can not download, no build instructions

### ISSUE THREAD

**Issue by xcambar** [kmgrant/macterm#1]
Hi,
I wish I could give MacTerm a try, but unfortunately:

* The download links in the website for 4.0 and 4.1-beta don't work
* There's no release available in Github
* The brew formula is available but doesn't work: tried both `brew cask install macterm` and `brew install Caskroom/cask/macterm`
* There's no README nor any kind of build instructions

Looking forward to reading from you,

**Comment by kmgrant** [comment]
Hi Xavier,

Thank you for your interest.

Do the files not download at all, or do they not open after downloading?

I tried the links below just now (from Firefox) and they work for me.

The download link for 4.1 beta is:
    http://www.macterm.net/updates/macterm-latest.dmg

And the older 4.0.0 link is:
    http://www.macterm.net/updates/macterm-4.0.0.dmg

I don’t maintain cask files but as far as I can tell cask refers to the same links.


It may help to open the Console application and look for any errors (maybe a network connection problem?).


Let me know,
Thanks
Kevin G.

**Comment by xcambar** [comment]
Thank you, the links you provided work and the links on the website do work as well, it probably only was a hiccup.

FYI, here's the homebrew output:

```
$ brew cask install Caskroom/cask/macterm
Error: Cask 'macterm' definition is invalid: Bad header line: parse failed
```

**Comment by kmgrant** [comment]
No problem.  I am glad you got it working.

Note that I don’t maintain "cask" files and I do not know where to look for them.  It sounds from the description like there is a simple typo so maybe the cask project can fix that file based on some other file?

**Comment by kmgrant** [comment]
Also, regarding a README and build instructions; please note that at the top of the source tree there are various text files, including "_AboutTheProject.txt", and "_Building.txt".

I will close this issue since you were eventually able to download the program and I don't have any control over external "cask" files.
