### ISSUE TITLE
Sixel support not detected.

### ISSUE THREAD

**Issue by hackerb9** [kmgrant/macterm#3]
Hi, I'm the author of [lsix](https://github.com/hackerb9/lsix) and I got a bug report saying that images are not showing up with MacTerm. https://github.com/hackerb9/lsix/issues/4

I apologize, but I do not have a Macintosh to test this on my self. It would appear that MacTerm is not responding to the Send Device Attributes escape sequence (`Esc [ c`) with a code that signifies that it is SIXEL capable. In particular, it should include the number 4 in the semicolon separated list. 

Here is a `bash` fragment you can cut and paste into MacTerm to see if it works:

    read -s -t 1 -d "c" -p $'\e[c'; echo $REPLY | cat -v | grep --color ';4;' && echo 'Captain, we get sixel!' || echo 'What you say? Main screen turn on.'

Using XTerm(312) on a Debian GNU/Linux box, I get the following:

    ^[[?63;1;2;4;6;9;15;22
    Captain, we get sixel!

As you can see, it is properly identifying itself as SIXEL capable.

**Comment by hackerb9** [comment]
Odd. The VT220 reply string you mentioned should work. That is the default response from MacTerm to `\e[c`? And Sixels are enabled by default in MacTerm?

**Comment by kmgrant** [comment]
The chosen terminal type will affect queries.  The default terminal type is actually VT100, and Preferences must be used to change this (for example, editing the Default in the Terminals category to select another emulator from the Emulation tab, and then opening a new window).

Sixels are enabled by default but VT100/VT102 emulators do not have a way to report that Sixels are present.

The reply above is generally what the VT220 or XTerm will return (there can also be a `1;` for 132-column mode).  The VT102 returns `\e[?6c` (always) and the VT100 returns `\e[?1;6c`.

I will probably change the default type to XTerm for MacTerm 5.  The VT100 default has been there a long time, before XTerm or Sixels or even some of the VT220 features were implemented.

**Comment by hackerb9** [comment]
Okay, that sounds good. So, if I get any more questions about MacTerm not working, I'll tell people to change the default terminal type to VT220.

By the way, how do I programmatically detect MacTerm? Can I check for an environment variable like TERM==macterm?

**Comment by kmgrant** [comment]
Yes, I think the terminal type is probably the issue.

To detect MacTerm specifically, you can check the `$TERM_PROGRAM` environment variable, which will be set to `MacTerm`.  (This seems to be set fairly consistently on the Mac; I noticed that the default Apple Terminal sets this to `Apple_Terminal`, and iTerm2 sets it to `iTerm.app`.)

Similarly, all of these terminal applications will set `$TERM_PROGRAM_VERSION` but the value varies; in MacTerm it will be the build number, which is a date such as `20180825`.

**Comment by hackerb9** [comment]
Perfect. Thank you.
